#@data/values
#! https://github.com/k14s/ytt/blob/master/examples/data-values/values.yml
#! If necessary, these values can be overwritten in a number of ways: https://github.com/k14s/ytt/blob/master/docs/ytt-data-values.md
---
name: ten
replicas: 6 #! worker nodes * 2
http_port: 80
fqdn: ten.changelog.com
image: thechangelog/ten:2019-12-31T20.20.10Z
