version: "3.6"

services:
  db:
    image: postgres:9.5.4
    # https://docs.docker.com/compose/compose-file/#expose
    expose:
      - "5432"
    # https://docs.docker.com/compose/compose-file/#volumes
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./priv:/app/priv
  app:
    # Keep this in lock-step with docker/Dockerfile.production
    image: thechangelog/runtime:2019-11-27T16.20.17Z
    working_dir: /app
    command: bash -exec "mix deps.get && ( if (mix deps | grep 'mix deps.compile' 1>/dev/null); then mix deps.compile; fi ) && (cd assets && yarn install) && mix do ecto.create, ecto.migrate, phx.server"
    environment:
      DB_HOST: db
      DB_NAME: changelog_dev
      DB_USER: postgres
      VIRTUAL_HOST: &host "${HOST:-localhost}"
      HOST: *host
    # https://docs.docker.com/compose/compose-file/#ports
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    depends_on:
      - db

volumes:
  postgres:
