#@ load("@ytt:data", "data")
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uploads
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: #@ data.values.app.uploads_volume_size
  storageClassName: linode-block-storage-retain
