#@ load("@ytt:data", "data")
apiVersion: "acid.zalan.do/v1"
kind: postgresql
metadata:
  #! Must be of format {team}-{name}
  name: changelog-db
  namespace: #@ data.values.namespace
spec:
  teamId: changelog
  users:
    changelog:
    - superuser
    - createdb
  volume:
    size: 10Gi
    storageClass: linode-block-storage
  numberOfInstances: 2
  databases:
    db: db
  postgresql:
    version: "12"
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  #! enableLogicalBackup: true
  #! https://crontab.guru/every-6-hours
  #! logicalBackupSchedule: "0 0/6 * * *"
  #! TODO: configLogicalBackup
