#@ load("@ytt:data", "data")
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations:
  name: tls-sync-fastly
  namespace: #@ data.values.namespace
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
              - /bin/sh
              - -c
            args:
#! https://github.com/k14s/ytt/issues/177
#@yaml/text-templated-strings
              - |-
                #! https://developer.fastly.com/reference/api/tls/custom-certs/private-keys/
                cat > /tmp/key.json <<EOF
                {
                  "data": {
                    "type": "tls_private_key",
                    "attributes": {
                      "key": "$(echo "$TLS_KEY" | awk '{ printf "%s\\n", $0 }')",
                      "name": "changelog.com"
                    }
                  }
                }
                EOF
                curl --verbose --silent \
                  --header "Accept: application/vnd.api+json" \
                  --header "Content-Type: application/vnd.api+json" \
                  --header "Fastly-Key: $FASTLY_API_TOKEN" \
                  --data @/tmp/key.json \
                  https://api.fastly.com/tls/private_keys

                #! https://developer.fastly.com/reference/api/tls/custom-certs/certificates/
                cat > /tmp/crt.json <<EOF
                {
                  "data": {
                    "type": "tls_certificate",
                    "attributes": {
                      "cert_blob": "$(echo "$TLS_CRT" | awk '{ printf "%s\\n", $0 }')",
                      "name": "changelog.com"
                    }
                  }
                }
                EOF
                curl --verbose --silent \
                  --header "Accept: application/vnd.api+json" \
                  --header "Content-Type: application/vnd.api+json" \
                  --header "Fastly-Key: $FASTLY_API_TOKEN" \
                  --request PATCH \
                  --data @/tmp/crt.json \
                  https://api.fastly.com/tls/certificates/(@= data.values.fastly.certificate_id @)

                if [ -n "$DEBUG" ]
                then
                  while true; do sleep 3600; done
                fi
            env:
              - name: DEBUG
                value: #@ data.values.debug
              - name: TLS_KEY
                valueFrom:
                  secretKeyRef:
                    name: wildcard-acme-tls
                    key: tls.key
              - name: TLS_CRT
                valueFrom:
                  secretKeyRef:
                    name: wildcard-acme-tls
                    key: tls.crt
              - name: FASTLY_API_TOKEN
                valueFrom:
                  secretKeyRef:
                    name: fastly
                    key: token
            image: curlimages/curl:7.72.0
            imagePullPolicy: IfNotPresent
            name: tls-sync-fastly
          restartPolicy: Never
  #! https://crontab.guru/#0_9_*_*_*
  schedule: 0 9 * * *
  successfulJobsHistoryLimit: 3
  suspend: false

