---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: db-local-ssd
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: ${NAMESPACE}
spec:
  clusterIP: None
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
      targetPort: postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: db
  namespace: ${NAMESPACE}
spec:
  serviceName: db
  selector:
    matchLabels:
      app: postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      affinity:
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: app
                    operator: In
                    values:
                      - postgres
              topologyKey: "kubernetes.io/hostname"
      # initContainers:
      #   - name: download-last-db-backup
      #     image: thechangelog/backups:202104
      #     imagePullPolicy: Always
      #     command: ["/usr/local/bin/download_last_db_backup"]
      #     workingDir: "/docker-entrypoint-initdb.d"
      #     env:
      #       - name: AWS_ACCESS_KEY_ID
      #         valueFrom:
      #           secretKeyRef:
      #             name: backups-aws
      #             key: access_key_id
      #       - name: AWS_SECRET_ACCESS_KEY
      #         valueFrom:
      #           secretKeyRef:
      #             name: backups-aws
      #             key: secret_access_key
      #       - name: AWS_REGION
      #         value: us-east-1
      #       - name: AWS_S3_BUCKET
      #         value: changelog-com-backups
      #     volumeMounts:
      #       - name: docker-entrypoint-initdb
      #         mountPath: "/docker-entrypoint-initdb.d"
      containers:
        - name: postgres
          # https://hub.docker.com/_/postgres
          image: postgres:12.6
          resources:
            requests:
              cpu: 4
              memory: 8Gi
            limits:
              cpu: 4
              memory: 8Gi
          ports:
            - containerPort: 5432
              name: postgres
          volumeMounts:
            - name: db-local-ssd
              mountPath: /var/lib/postgresql/data
            - name: docker-entrypoint-initdb
              mountPath: "/docker-entrypoint-initdb.d"
          env:
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_DB
              value: changelog
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres
                  key: password
      volumes:
        - name: db-local-ssd
          persistentVolumeClaim:
            claimName: db-local-ssd
        - name: docker-entrypoint-initdb
          emptyDir: {}
