---
# TODO: manage changelog.com when:
# - multiple IPs (a.k.a. targets) are supported (for DNSimple?)
# - AAAA records are supported: https://github.com/kubernetes-sigs/external-dns/issues/2044#issuecomment-830674918
apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: 22.changelog.com
  namespace: ${NAMESPACE}
spec:
  endpoints:
  - dnsName: 22.changelog.com
    recordTTL: ${DNS_TTL}
    recordType: A
    targets:
      - ${PUBLIC_IPv4}
