---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: app
  namespace: ${NAMESPACE}
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
    external-dns.alpha.kubernetes.io/ttl: "${DNS_TTL}"
spec:
  tls:
    - hosts:
        - "changelog.com"
        - "*.changelog.com"
      secretName: wildcard-acme-tls
  rules:
    - host: "22.changelog.com"
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: app
                port:
                  number: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: app
  namespace: ${NAMESPACE}
  labels:
    app: app
spec:
  ports:
    - name: http
      port: 4000
      protocol: TCP
      targetPort: phoenix
  selector:
    app: app
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: wildcard-acme-tls
  namespace: ${NAMESPACE}
spec:
  dnsNames:
    - '*.changelog.com'
    - 'changelog.com'
  issuerRef:
    name: cert-manager-webhook-dnsimple-production
    kind: ClusterIssuer
  secretName: wildcard-acme-tls
