apiVersion: v1
kind: Namespace
metadata:
  name: ten-changelog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ten-changelog
  namespace: ten-changelog
  labels:
    app: ten-changelog
spec:
  replicas: 6
  selector:
    matchLabels:
      app: ten-changelog
  template:
    metadata:
      labels:
        app: ten-changelog
    spec:
      containers:
      - image: thechangelog/ten:2019-11-01T10.10.10Z
        ports:
        - name: http
          containerPort: 80
        name: ten-changelog
        readinessProbe:
          tcpSocket:
            port: http
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ten-changelog
  namespace: ten-changelog
  annotations:
    external-dns.alpha.kubernetes.io/hostname: ten.changelog.com
spec:
  selector:
    app: ten-changelog
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
