version: "3.7"
#
# https://docs.docker.com/engine/swarm/configs/
configs:
  netdata_config:
    file: ./netdata/netdata.local.conf
  netdata_nginx_config:
    file: ./netdata/nginx.conf

# https://docs.docker.com/compose/compose-file/#volumes
volumes:
  changelog.com:

# https://docs.docker.com/engine/swarm/secrets/#defining-and-using-secrets-in-compose-files
secrets:
  CM_API_TOKEN_2:
    external: true
  CM_SMTP_TOKEN:
    external: true
  GITHUB_API_TOKEN2:
    external: true
  GITHUB_CLIENT_ID:
    external: true
  GITHUB_CLIENT_SECRET:
    external: true
  HN_USER_1:
    external: true
  HN_PASS_1:
    external: true
  TWITTER_CONSUMER_KEY:
    external: true
  TWITTER_CONSUMER_SECRET:
    external: true
  SECRET_KEY_BASE:
    external: true
  SIGNING_SALT:
    external: true
  SLACK_INVITE_API_TOKEN:
    external: true
  SLACK_APP_API_TOKEN:
    external: true
  ROLLBAR_ACCESS_TOKEN:
    external: true
  BUFFER_TOKEN_3:
    external: true
  COVERALLS_REPO_TOKEN:
    external: true
  ALGOLIA_APPLICATION_ID:
    external: true
  ALGOLIA_API_KEY2:
    external: true
  PLUSPLUS_SLUG_1:
    external: true

services:
  # log:
  #   command: syslog+tls://logs7.papertrailapp.com:14349
  #   deploy:
  #     mode: global
  #     restart_policy:
  #       condition: any
  #     # https://docs.docker.com/compose/compose-file/#resources
  #     # https://docs.docker.com/config/containers/resource_constraints/
  #     resources:
  #       reservations:
  #         cpus: "0.5"
  #         memory: 128M
  #       limits:
  #         cpus: "0.5"
  #         memory: 128M
  #     update_config:
  #       failure_action: rollback
  #       # start_period + (interval * retries)
  #       monitor: 50s
  #       order: start-first
  #   healthcheck:
  #     test: ["CMD", "wget", "--output-document", "/dev/null", "--quiet",  "http://127.0.0.1:80/health"]
  #     interval: 15s
  #     timeout: 15s
  #     retries: 3
  #     start_period: 5s
  #   environment:
  #     SYSLOG_HOSTNAME: "${USER}.localhost"
  #   image: gliderlabs/logspout:latest
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  db:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      POSTGRES_USER: &pg_user postgres
      POSTGRES_DB: &pg_db changelog
      # https://www.postgresql.org/docs/9.5/libpq-envars.html
      PGUSER: *pg_user
      PGDATABASE: *pg_db
    healthcheck:
      test: ["CMD", "pg_isready"]
      start_period: 30s
    image: postgres:9.5.4
    volumes:
      - ${PWD}/priv/db:/var/lib/postgresql/data:rw
  # db_backup:
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #       delay: 10s
  #       max_attempts: 3
  #       window: 15s
  #     # https://docs.docker.com/compose/compose-file/#resources
  #     # https://docs.docker.com/config/containers/resource_constraints/
  #     resources:
  #       reservations:
  #         cpus: "0.5"
  #         memory: 128M
  #       limits:
  #         cpus: "0.5"
  #         memory: 128M
  #     update_config:
  #       failure_action: rollback
  #       monitor: 15s
  #       order: stop-first
  #   depends_on:
  #     - db
  #   environment:
  #     # https://www.postgresql.org/docs/9.5/libpq-envars.html
  #     PGHOST: db
  #     PGUSER: *pg_user
  #     PGDATABASE: *pg_db
  #     AWS_REGION: "us-east-1"
  #     AWS_S3_BUCKET: "changelog-com-backups-dev"
  #     BACKUP_DB_EVERY_N_SECONDS: 60
  #     BACKUPS_AWS_ACCESS_KEY: "no"
  #     BACKUPS_AWS_SECRET_KEY: "way"
  #     image: thechangelog/db_backup:201910
  app:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      # https://docs.docker.com/compose/compose-file/#update_config
      update_config:
        failure_action: rollback
        # start_period + (interval * retries)
        monitor: 180s
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "--output", "/dev/null", "--fail", "--fail-early",  "--silent",  "http://127.0.0.1:4000/health"]
      interval: 15s
      timeout: 15s
      retries: 4
      start_period: 120s
    environment:
      MAKEFILE: Makefile.201910
      NODE: "${HOSTNAME}"
      DB_URL: "ecto://postgres@db:5432/changelog"
      DB_HOST: db
      DB_NAME: *pg_db
      DB_USER: *pg_user
      PORT: 4000
      URL_HOST: &host "changelog.localhost"
      URL_PORT: 80
      URL_SCHEME: http
      URL_STATIC_HOST: *host
      ROLLBAR_ENVIRONMENT: local
    secrets:
      - CM_API_TOKEN_2
      - CM_SMTP_TOKEN
      - GITHUB_API_TOKEN2
      - GITHUB_CLIENT_ID
      - GITHUB_CLIENT_SECRET
      - HN_USER_1
      - HN_PASS_1
      - TWITTER_CONSUMER_KEY
      - TWITTER_CONSUMER_SECRET
      - SECRET_KEY_BASE
      - SIGNING_SALT
      - SLACK_INVITE_API_TOKEN
      - SLACK_APP_API_TOKEN
      - ROLLBAR_ACCESS_TOKEN
      - BUFFER_TOKEN_3
      - COVERALLS_REPO_TOKEN
      - ALGOLIA_APPLICATION_ID
      - ALGOLIA_API_KEY2
      - PLUSPLUS_SLUG_1
    depends_on:
      - db
    image: thechangelog/changelog.com:local
    ports:
      - "4000:4000"
    volumes:
      - ${PWD}/priv/uploads:/uploads:rw
  # app_updater:
  #   deploy:
  #     replicas: 1
  #     restart_policy:
  #       condition: on-failure
  #       max_attempts: 3
  #     # https://docs.docker.com/compose/compose-file/#resources
  #     # https://docs.docker.com/config/containers/resource_constraints/
  #     resources:
  #       reservations:
  #         cpus: "0.5"
  #         memory: 128M
  #       limits:
  #         cpus: "0.5"
  #         memory: 128M
  #     # https://docs.docker.com/compose/compose-file/#update_config
  #     update_config:
  #       failure_action: rollback
  #       monitor: 30s
  #       order: stop-first
  #   command: update_service_continuously
  #   environment:
  #     HOSTNAME: "${HOSTNAME}"
  #     UPDATE_SERVICE_EVERY_N_SECONDS: 10
  #     DOCKER_SERVICE_IMAGE: thechangelog/changelog.com:local
  #   image: thechangelog/bootstrap:201910
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock:ro
  #     - changelog.com:/app:rw
  proxy:
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      # https://docs.docker.com/compose/compose-file/#resources
      # https://docs.docker.com/config/containers/resource_constraints/
      resources:
        reservations:
          cpus: "2"
          memory: 2G
        limits:
          cpus: "2"
          memory: 2G
      update_config:
        failure_action: rollback
        # start_period + interval
        monitor: 20s
        order: start-first
    healthcheck:
      test: ["CMD", "nginx", "-t"]
      interval: 10s
      timeout: 10s
      retries: 0
      start_period: 5s
    image: thechangelog/proxy
    environment:
      DEFAULT_HOST: *host
    ports:
      - "80:80"
    volumes:
      - ${PWD}/priv/uploads:/var/www/uploads:ro
  netdata:
    configs:
      - source: netdata_config
        target: /etc/netdata/netdata.conf
      - source: netdata_nginx_config
        target: /etc/netdata/python.d/nginx.conf
    deploy:
      replicas: 1
      restart_policy:
        condition: any
      # https://docs.docker.com/compose/compose-file/#resources
      # https://docs.docker.com/config/containers/resource_constraints/
      resources:
        reservations:
          cpus: "1"
          memory: 128M
        limits:
          cpus: "1"
          memory: 128M
      update_config:
        failure_action: rollback
        # start_period + (interval * retries)
        monitor: 75s
        order: start-first
    healthcheck:
      test: ["CMD", "curl", "--output", "/dev/null", "--fail", "--fail-early",  "--silent",  "http://127.0.0.1:19999/"]
      interval: 15s
      timeout: 15s
      retries: 3
      start_period: 30s
    image: netdata/netdata
    hostname: local_netdata
    environment:
      # netdata container is too verbose, tell Logspout to not send logs to Papertrail
      # https://github.com/gliderlabs/logspout#ignoring-specific-containers
      LOGSPOUT: ignore
    ports:
      - "19999:19999"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
