#@data/values
#! https://github.com/k14s/ytt/blob/master/examples/data-values/values.yml
#! If necessary, these values can be overwritten in a number of ways: https://github.com/k14s/ytt/blob/master/docs/ytt-data-values.md
---
#! https://access.crunchydata.com/documentation/postgres-operator/4.4.0/installation/postgres-operator/#configuration-postgres-operator-yml
#! Certificates will only be created if action is install.
#! Change to update if already installed.
action: install
metrics: "true"
storage:
  persistentretain:
    type: linode-block-storage-retain
    size: 10Gi
  persistent:
    type: linode-block-storage
    size: 10Gi
  local:
    type: local-storage
    size: 10Gi
#! provided just-in-time
namespace:
managed_namespaces:
version:
