apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: keel22.changelog.com
  namespace: ${NAMESPACE}
spec:
  endpoints:
  - dnsName: keel22.changelog.com
    recordTTL: ${DNS_TTL}
    recordType: A
    targets:
      - ${PUBLIC_IPv4}
