#@ load("@ytt:data", "data")
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kube-prometheus-stack-changelog-app
  namespace: #@ data.values.namespace
  labels:
    app: kube-prometheus-stack-changelog-app
spec:
  endpoints:
    - path: /metrics
      port: http
      bearerTokenFile: /var/run/secrets/promex/bearer_token
  jobLabel: app
  selector:
    matchLabels:
      app: #@ data.values.changelog.app.name
  namespaceSelector:
    matchNames:
      - #@ data.values.changelog.app.namespace
