#@ load("@ytt:data", "data")
#! https://github.com/k14s/ytt/blob/master/examples/data-values/config.yml
defaultRules:
  rules:
    alertmanager: false

alertmanager:
  enabled: false

prometheus:
  prometheusSpec:
    scrapeInterval: 15s
    retention: 30d
    size: 10GB
    resources:
      requests:
        cpu: 1
        memory: 1Gi
      limits:
        cpu: 2
        memory: 4Gi
    additionalScrapeConfigs:
      #! Example scrape config for pods
      #!
      #! The relabeling allows the actual pod scrape endpoint to be configured via the
      #! following annotations:
      #!
      #! * `prometheus.io/scrape`: Only scrape pods that have a value of `true`
      #! * `prometheus.io/path`: If the metrics path is not `/metrics` override this.
      #! * `prometheus.io/port`: Scrape the pod on the indicated port instead of the default of `9102`.
      - job_name: 'kubernetes-pods'
        kubernetes_sd_configs:
          - role: pod
        relabel_configs:
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
            action: keep
            regex: true
          - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
            action: replace
            target_label: __metrics_path__
            regex: (.+)
          - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
            action: replace
            regex: ([^:]+)(?::\d+)?;(\d+)
            replacement: $1:$2
            target_label: __address__
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels: [__meta_kubernetes_namespace]
            action: replace
            target_label: kubernetes_namespace
          - source_labels: [__meta_kubernetes_pod_name]
            action: replace
            target_label: kubernetes_pod_name
          - source_labels: [__meta_kubernetes_pod_phase]
            regex: Pending|Succeeded|Failed
            action: drop
    #! TODO: enable metrics forwarding when @adamstac says that we are ready
    #! remoteWrite:
    #!  - name: grafana-cloud
    #!    url: #@ data.values.grafana_cloud.url
    #!    basicAuth:
    #!      username:
    #!        name: grafana-cloud
    #!        key: username
    #!      password:
    #!        name: grafana-cloud
    #!        key: password

grafana:
  enabled: true
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: nginx
      cert-manager.io/cluster-issuer: cert-manager-webhook-dnsimple-production
      external-dns.alpha.kubernetes.io/ttl: "60"
    hosts:
      - #@ data.values.fqdn
    tls:
      - secretName: wildcard-acme-tls
        hosts:
          - #@ data.values.fqdn
  persistence:
    enabled: true
    size: 10Gi
    storageClassName: linode-block-storage
  grafana.ini:
    auth:
      oauth_auto_login: true
      disable_login_form: true
    auth.anonymous:
      enabled: false
    auth.github:
      allow_sign_up: true
      allowed_organizations: #@ data.values.github.allowed_organizations
      client_id: #@ data.values.github.client_id
      client_secret: #@ data.values.github.client_secret
      enabled: true
      team_ids: #@ data.values.github.team_ids
    security:
      disable_initial_admin_creation: true
    server:
      enable_gzip: true
      root_url: #@ "https://" + data.values.fqdn
    users:
      auto_assign_org_role: Admin
