# Inspired by https://github.com/fly-apps/live_beats/blob/master/fly.toml
app = "changelog-2022-03-13"

kill_signal = "SIGTERM"
kill_timeout = 5

[build]
  image = "thechangelog/changelog.com:2022.fly"

[deploy]
  strategy = "bluegreen"

[env]
  AWS_ASSETS_BUCKET = "changelog-assets"
  AWS_REGION = "us-east-1"
  AWS_UPLOADS_HOST = "https://changelog-assets.s3.amazonaws.com"
  GRAFANA_DATASOURCE_ID = "grafanacloud-changelog-prom"
  GRAFANA_URL = "https://changelog.grafana.net"
  PORT = "4000"
  STATIC_URL_HOST = "cdn.changelog.com"
  URL_HOST = "changelog.com"

[[services]]
  internal_port = 4000
  processes = ["app"]
  protocol = "tcp"

  [[services.http_checks]]
    grace_period = "120s"
    interval = 15000
    method = "get"
    path = "/health"
    protocol = "http"
    timeout = 10000

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
