apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  # Must be of format {team}-{name}
  name: changelog-db
  namespace: ${NAMESPACE}
spec:
  teamId: changelog
  users:
    changelog:
    - superuser
    - createdb
  volume:
    size: 10Gi
    storageClass: local-path
  numberOfInstances: 1
  databases:
    db: db
  postgresql:
    version: "12"
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "2"
      memory: "4Gi"
  # enableLogicalBackup: true
  # https://crontab.guru/every-6-hours
  # logicalBackupSchedule: "0 0/6 * * *"
  # TODO: configLogicalBackup
