apiVersion: v1
kind: Namespace
metadata:
  name: ${NAMESPACE}
---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  annotations: null
  name: tls-sync-fastly
  namespace: ${NAMESPACE}
spec:
  concurrencyPolicy: Forbid
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
          - command:
            - /bin/sh
            - -c
            args:
            - |-
              if [ -n "${DEBUG}" ]
              then
                CURL_OPTIONS="--verbose"
              else
                echo "Fail job on error..."
                set -e
                set -o pipefail
              fi

              #! https://developer.fastly.com/reference/api/tls/custom-certs/private-keys/
              cat > /tmp/key.json <<EOF
              {
                "data": {
                  "type": "tls_private_key",
                  "attributes": {
                    "key": "$$(echo "$$TLS_KEY" | awk '{ printf "%s\\n", $$0 }')",
                    "name": "changelog.com"
                  }
                }
              }
              EOF
              echo "But don't fail POST-ing private keys, as it's not idempotent"
              echo "This Fastly support ticket has all the details: https://support.fastly.com/hc/en-us/requests/329710"
              echo "TODO: What is the simplest way of checking that a private key exists?"
              curl $$CURL_OPTIONS --silent --show-error \
                --header "Accept: application/vnd.api+json" \
                --header "Content-Type: application/vnd.api+json" \
                --header "Fastly-Key: $$FASTLY_API_TOKEN" \
                --data @/tmp/key.json \
                https://api.fastly.com/tls/private_keys 2>&1 | grep -v "$$FASTLY_API_TOKEN"

              #! https://developer.fastly.com/reference/api/tls/custom-certs/certificates/
              cat > /tmp/crt.json <<EOF
              {
                "data": {
                  "type": "tls_certificate",
                  "attributes": {
                    "cert_blob": "$$(echo "$$TLS_CRT" | awk '{ printf "%s\\n", $$0 }')",
                    "name": "changelog.com"
                  }
                }
              }
              EOF
              curl $$CURL_OPTIONS --silent --fail --show-error \
                --header "Accept: application/vnd.api+json" \
                --header "Content-Type: application/vnd.api+json" \
                --header "Fastly-Key: $$FASTLY_API_TOKEN" \
                --request PATCH \
                --data @/tmp/crt.json \
                https://api.fastly.com/tls/certificates/1LA0UjkMfnnMwzglSLdAc 2>&1 | grep -v "$$FASTLY_API_TOKEN"

              if [ -n "${DEBUG}" ]
              then
                while true; do sleep 3600; done
              fi
            env:
            - name: TLS_KEY
              valueFrom:
                secretKeyRef:
                  name: wildcard-acme-tls
                  key: tls.key
            - name: TLS_CRT
              valueFrom:
                secretKeyRef:
                  name: wildcard-acme-tls
                  key: tls.crt
            - name: FASTLY_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: fastly
                  key: token
            image: curlimages/curl:7.72.0
            imagePullPolicy: IfNotPresent
            name: tls-sync-fastly
          restartPolicy: Never
  schedule: 0 9 * * *
  successfulJobsHistoryLimit: 3
  suspend: false
