# Global Configurations
global:
  scrape_interval:     5s
  evaluation_interval: 5s

# Targets to scrape
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'changelog_app'
    bearer_token: 'super_secret_metrics'
    static_configs:
      - targets:
        - 'changelog_app:4000'
